package example;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import org.junit.jupiter.api.Test;

// AUTOGENERATED - review
public class CalculatorAutoTest {

    @Test
    public void testAdd() {
        Calculator c = new Calculator();
        assertEquals(5, c.add(2, 3));
        assertEquals(0, c.add(0, 0));
        assertEquals(-1, c.add(-2, 1));
    }

    @Test
    public void testSubtract() {
        Calculator c = new Calculator();
        assertEquals(-1, c.subtract(2, 3));
        assertEquals(2, c.subtract(2, 0));
    }

    @Test
    public void testDivideNormal() {
        Calculator c = new Calculator();
        assertEquals(2, c.divide(6, 3));
        assertEquals(0, c.divide(0, 5));
    }

    @Test
    public void testDivideByZero() {
        Calculator c = new Calculator();
        assertThrows(IllegalArgumentException.class, () -> c.divide(1, 0));
    }

}
